ai_services:
  openai:
    api_key: sk-abcd1234efgh5678ijkl9012mnop3456qrst7890uvwx1234yzab
    organization: org-abcdefghijklmnopqrstuvwx
    model: gpt-4
    temperature: 0.7

  anthropic:
    api_key: sk-ant-abcd1234efgh5678ijkl9012mnop3456qrst7890
    model: claude-2
    max_tokens: 1000

  gemini:
    api_key: AIzaABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abc
    project_id: test-project
    location: us-central1

vector_databases:
  pinecone:
    api_key: pinecone-abcdefghijklmnopqrstuvwxyz
    environment: us-west1-gcp
    index_name: semantic-search

  weaviate:
    api_key: weaviate-1234567890abcdefghijklmnop
    url: https://test-instance.weaviate.network

model_settings:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  device: cuda 